{
 "title": "Mastodon",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Queue size",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mastodon_sidekiq_enqueued", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mastodon_sidekiq_queues_latency",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Processing time",
   "type": "stat",
   "description": "Processing time of jobs, average of all workers",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(mastodon_sidekiq_workers_processing_time)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sidekiq", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Queue sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "mastodon_sidekiq_queues_enqueued",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "mastodon_sidekiq_queues_latency",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Processed jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "irate(Mastodon_production_sidekiq_processed[$__interval])",
     "legendFormat": "Processed"
    },
    {
     "expr": "irate(Mastodon_production_sidekiq_failed[1m])",
     "legendFormat": "Failed"
    },
    {
     "expr": "rate(mastodon_sidekiq_processed[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(mastodon_sidekiq_failed[$__rate_interval])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Failed jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(mastodon_sidekiq_workers_failure[$__rate_interval])",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Successful jobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(mastodon_sidekiq_workers_success[$__rate_interval])",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Worker processing time p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "mastodon_sidekiq_workers_processing_time{quantile=\"0.99\"}",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Response codes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(mastodon_web_request_status[$__rate_interval])",
     "legendFormat": "{{controller}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Request total duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "mastodon_web_request_total_duration",
     "legendFormat": "{{controller}} [{{action}} {{format}}]"
    }
   ]
  },
  {
   "title": "Queries by table",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(table) (mastodon_db_query)",
     "legendFormat": "{{table}}"
    }
   ]
  }
 ]
}